### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by MatiasOS**

### CODE REVIEW

**Comment by JirkaChadima** [comment]
@MatiasOS Could you set the nodejs version and a dsitribution as well? See wt-contracts's .travis

Than ask @AugustoL to turn this repository on on travis-ci.org, the builds should then appear [here](https://travis-ci.org/windingtree/wt-nodejs-api)

**Comment by AugustoL** [comment]
Travis enabled on this repo.

**Comment by MatiasOS** [comment]
@JirkaChadima It's not necesaray. If the travis file don't specify the version, It uses the one in `.nvmrc`.

**Comment by JirkaChadima** [comment]
@MatiasOS Did not know that!

**Pull request merged**
