### PR TITLE
Multiple wallet support

### PR DESCRIPTION
**Pull request by JirkaChadima**
This PR should add a support for multiple wallets handled by a single API instance.

*We know that managing wallets locally on an API instance is a bad idea. But we've decided to go with it for demo and testing purposes.*

**TODO list**

- [x] Handling IO errors
- [x] Picking a proper wallet for each request (probably based on a header?)
- [x] Any wallet-related operation requires a wallet password. Wallet can never be manipulated with without successful decryption
- [x] Get rid of the configuration's `privateKeyFile`
- [x] Use `res.locals` instead of `req.wt` to pass wallets and other WT related stuff around a single request (http://expressjs.com/en/api.html#res.locals). Also we should check when/how this gets destroyed during the request lifecycle.
- [x] POST /wallets - body contains the keyfile, password is in a header. The endpoint tries to decrypt the file and if it succeeds, the wallet is stored under <uuid>.json. These files can furthermore be encrypted with a server-side configured per-instance secret.
- [x] DELETE /wallets/:uuid - password is in header. If we find the file and are able to decrypt it, wallet gets deleted. Otherwise nothing happens.
- [x] GET /wallets/:uuid - password is in header. If we find the file and are able to decrypt it, we return 200. Otherwise we return 404 or 401. This endpoint should probably be throttled to prevent brute force attacks on wallet passwords.
- [x] Make sure every wallet is locked (or maybe destroyed) again ASAP to reduce the unlocked wallet lifespan to a total minimum
- [x] Encrypting JSON keyfiles on disk with a configuration-provided and instance-specific secret
- [x] Throttling
- [x] Update swagger

### CODE REVIEW

**Comment by AugustoL** [comment]
Cool, as far as for the endpoints to be used I think we would only need /add, /remove and /list for wallet management.

The `/add` endpoint can receive the account and a signed message by this account. We check the signature is right in the API and we add it to the API wallets.
The `/remove` endpoint will receive the address of the wallet to remove and a signed message by the account owner, if the message is signed by the account it gets remove form the API.
The `/list` endpoint will just return a list of the addresses of the accounts registered in the API.

Every endpoint that needs a wallet to be decrypted should receive `address` and `password` in header, will get the right account from the API and decrypt it with the password provided.

WDYT @JirkaChadima ?

**Comment by AugustoL** [comment]
@JirkaChadima yes, uuids is a better idea.

About the check or verify instead address I agree thats better too.

My idea was to request teh signed message in `/add` and `/remove` endpoints. But I guess just doing it with the password is enough.

**Comment by JirkaChadima** [comment]
OK, so I guess we're going to go with something like this:

- `POST /wallets` - body contains the keyfile, password is in a header. The endpoint tries to decrypt the file and if it succeeds, the wallet is stored under `<uuid>.json`. These files can furthermore be encrypted with a server-side configured per-instance secret.
- `DELETE /wallets/:uuid` - password is in header. If we find the file and are able to decrypt it, wallet gets deleted. Otherwise nothing happens.
- `GET /wallets/:uuid` - password is in header. If we find the file and are able to decrypt it, we return 200. Otherwise we return 404 or 401. This endpoint should probably be throttled to prevent brute force attacks on wallet passwords.

Sounds good @augustol?

**Comment by AugustoL** [comment]
@JirkaChadima sounds good

**Pull request merged**
